Load & functional tests
setday/HSE_ML_P2024 pull request #12
Opened 2024-05-05 12:59 UTC by yv0vaa

2024-05-24 19:08 UTC, Tematikys requested changes

2024-05-24 19:08 UTC, Tematikys commented on test_functional.py
> +        core.scene.car_m.health == 100
Почему именно 100

2024-05-24 19:08 UTC, Tematikys commented on test_functional.py
Не совсем понятно, что проверяют эти тесты. Если будет решено как-то изменить систему внутри Core, то эти тесты будут лишь мешать

2024-05-24 19:08 UTC, Tematikys commented on tests/test_functional.py
Дублирование кода

2024-05-24 19:08 UTC, Tematikys commented on tools/pytest/defs.bzl
Я не понял, зачем нужны эти файлы

2024-05-24 19:08 UTC, Tematikys commented on tools/pytest/pytest_wrapper.py
(этот)

2024-05-24 19:09 UTC, Tematikys commented
Много дублирующихся файлов из текущей версии main. Нужно как-то это исправить

2024-05-26 15:55 UTC, Tematikys approved these changes, later dismissed

2024-05-26 19:24 UTC, setday commented on tools/pytest/pytest_wrapper.py
Чтобы можно было запускать pytest через обычный питонавский run

2024-05-26 19:26 UTC, setday commented on test_functional.py
Да, так устроены типичные функциональные тесты. Ты пытаешься что-то изменить -> они мешают это сделать :)

2024-05-27 11:18 UTC, Tematikys approved these changes

2024-05-27 11:21 UTC, merged