AI
setday/HSE_ML_P2024 pull request #14
Opened 2024-05-26 13:27 UTC by yv0vaa

В папке gym_game - обертка для обучения моделей, models_bin - файлы с весами моделей (самая адекватно себя ведущая - РРО). AIController дописан для использования моделей. В папке notebooks:
1) CEM.ipynb - пайплайн обучения метода кросс-энтропии
2) SimpleDQN.ipynb - пайплайн обучения самописной DQN
3) stable_baselines.ipynb - пайплайн обучения моделей с помощью одноименного фреймворка. 
Перед обучением надо выбрать и написать функцию награды (метод evaluate класса gym_game/envs/Game.py)

2024-05-26 16:13 UTC, Tematikys requested changes
Неужели вся эта типизация настолько была нужна...
Может notebooks стоит вынести в полноценные python-программы?

2024-05-26 16:13 UTC, Tematikys commented on .github/workflows/CI.yml
Нужно уже определиться с форматированием подобных файлов, а то что ни PR, то новая версия

2024-05-26 16:13 UTC, Tematikys commented on assets/maps/ParkWithEnemies.json
Зачем удалены json'ы?

2024-05-26 16:13 UTC, Tematikys commented on gym_game/envs/Game.py
> +        car_pos = self.core.scene.car_m.car_model.body.position
Можно заменить на вызов observe

2024-05-26 16:13 UTC, Tematikys commented on gym_game/envs/Game.py
> +        controller.keyboard = {
Если модель умеет, то можно на каждое действие выделить по выходному узлу, чтобы не писать подобные сложные конструкции. Так даже у модельки будет больше контроля

2024-05-26 16:13 UTC, Tematikys commented on gym_game/envs/Game.py
> +        # self.time *= 1.01
Убрать ненужные комментарии?

2024-05-26 16:13 UTC, Tematikys commented on gym_game/envs/Game.py
> +        car_pos = self.core.scene.car_m.car_model.body.position
self.observe()

2024-05-26 16:13 UTC, Tematikys commented on requirements.txt
С requirements тоже стоит уже определиться, вроде тут не просто добавляются новые пункты

2024-05-26 16:13 UTC, Tematikys commented on src/game_engine/controllers/Controller.py
> +    def handle_input(self, keys: dict = None, observation: list[float] | np.ndarray = None) -> None:
Тут ещё раз видно, что лучше добавить активацию для нейронки на каждое действие, чтобы не городить вот такие махины

2024-05-26 16:13 UTC, Tematikys commented on src/game_engine/controllers/Controller.py
Навверное, стоит сделать наследование для каждой реализации нейронки, чтобы они не конфликтовали друг с другом (в том числе, для той, что сейчас в main)

2024-05-26 16:13 UTC, Tematikys commented on src/game_engine/scenes/game_scene/GameScene.py
> +                        Controller.AIController(random.choice([
Может вынести в отдельный массив?

2024-05-26 16:13 UTC, Tematikys commented on src/game_engine/scenes/game_scene/GameScene.py
> +            # print((self.car_m.car_model.body.position[0]
Убрать?

2024-05-26 16:13 UTC, Tematikys commented on src/game_engine/scenes/game_scene/GameScene.py
> +        # for cone in self.traffic_cones:
Убрать?

2024-05-26 16:13 UTC, Tematikys commented on test_functional.py
Кажется, функциональное тестирование уже есть в другой ветке

2024-05-26 19:27 UTC, setday commented
> Неужели вся эта типизация настолько была нужна...

Это принципы чистого кода (мы учимся писать понятный, отказоустойчивый код)

2024-05-26 19:28 UTC, setday commented
> Может notebooks стоит вынести в полноценные python-программы?

Они удобно отображают графики.

Т.к. нагрузочное тестирование больше исследовательское, ноутбуки подходят больше

2024-05-26 19:30 UTC, setday commented on requirements.txt
Да, их нужно почистить

2024-05-26 22:35 UTC, yv0vaa commented on assets/maps/ParkWithEnemies.json
Они дублировались. Было две папки с одинаковыми json-ами

2024-05-26 22:36 UTC, yv0vaa commented on gym_game/envs/Game.py
> +        car_pos = self.core.scene.car_m.car_model.body.position
Согласен

2024-05-26 23:02 UTC, yv0vaa commented on src/game_engine/controllers/Controller.py
Не уверен, что так будет лучше, по крайней мере с данной реализацией. Разница только в том, как модель предсказывает действия, остальной код из handle_input() будет дублироваться

2024-05-27 10:51 UTC, Tematikys requested changes

2024-05-27 10:51 UTC, Tematikys commented on src/game_engine/controllers/Controller.py
А как смёржить с моим кодом?.. Затереть?(

2024-05-27 10:51 UTC, Tematikys commented on src/game_engine/controllers/TrainAI.py
Так, а почему это новый файл..? Он же должен быть в main уже

2024-05-27 14:47 UTC, Tematikys approved these changes, later dismissed

2024-05-27 14:59 UTC, Tematikys approved these changes

2024-05-27 15:02 UTC, merged